require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'DS_POC_DEMO' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  target 'DS_POC_DEMOTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
    flipper_post_install(installer)
  end
end

target 'DS_POC_DEMO-tvOS' do
  # Pods for DS_POC_DEMO-tvOS

  target 'DS_POC_DEMO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
